import Head from "next/head";
import Image from "next/image";
import nftImagen from "public/images/image-equilibrium.jpg";
import imageAvatar from "public/images/image-avatar.png";
import iconEth from "public/images/icon-ethereum.svg";
import iconClock from "public/images/icon-clock.svg";
import iconView from "public/images/icon-view.svg";

export default function Home() {
  function iconViewDisplay() {
    const icon = document.querySelectorAll("img");
    icon[1].classList.remove("hidden");
    icon[1].classList.add("block");
  }
  function iconViewHide() {
    const icon = document.querySelectorAll("img");
    icon[1].classList.remove("block");
    icon[1].classList.add("hidden");
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className="bg-[#0D192B] h-full  flex items-center justify-center p-5">
        <div className="bg-[#14253D] max-w-[375px]  font-light p-5 flex flex-col gap-4 rounded-xl ">
          <div className="relative">
            <Image
              src={nftImagen}
              alt="nft pic"
              className="rounded-xl z-0"
            ></Image>
            <div
              className="hover:bg-[#00FFF7]/50 rounded-xl top-0 hover:cursor-pointer z-10 w-full h-full absolute flex items-center justify-center "
              onMouseOver={iconViewDisplay}
              onMouseLeave={iconViewHide}
            >
              <Image src={iconView} alt="" className="hidden"></Image>
            </div>
          </div>
          <h1 className="text-[#FFFFFF] text-lg font-semibold hover:text-[#00FFF7] hover:cursor-pointer">
            Equilibrium #3429
          </h1>
          <p>Our Equilibrium collection promotes balance and calm.</p>
          <div className="flex justify-between">
            <div className="flex items-center">
              <Image src={iconEth} alt="eth ico"></Image>
              <h2 className="text-[#00FFF7] ml-2">0.041 ETH</h2>
            </div>
            <div className="flex items-center">
              <Image src={iconClock} alt="clock ico"></Image>
              <p className="ml-2">3 days left</p>
            </div>
          </div>

          <div className="flex items-center border-t-[1px] pt-4 border-[#8bacda]/20">
            <Image
              src={imageAvatar}
              alt="avatar ico"
              className="border-2 rounded-full"
              width={35}
              height={35}
            ></Image>
            <p className="ml-3">
              Creation of{" "}
              <span className="text-[#FFFFFF] font-normal hover:cursor-pointer hover:text-[#00FFF7]">
                Jules Wyvern
              </span>{" "}
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
